### ISSUE TITLE
AI commands problem and disabling automatic update

### ISSUE THREAD

**Issue by irosyadi** [nbonamy/witsy#114]
Witsy 2.0 on Windows has a bug where the AI command's text copying function is broken, which worked fine in the previous version (1.4). 
Also, is there a way to turn off automatic updates?

**Comment by nbonamy** [comment]
Which OS are you on? Can you give more details about what is happening?

**Comment by irosyadi** [comment]
> Which OS are you on? Can you give more details about what is happening?

Windows 10. Selecting and triggering AI Commands on highlighted text copies the text and passes it as {input} to the selected command. This functionality worked in version 1.4 but is broken in version 2.0, producing the error "Please highlight the text you want to analyze" despite text being highlighted.

Unfortunately, Witsy automatically upgrades, which has resulted in the functionality that worked in version 1.4 being broken. As a workaround, users might consider temporarily disabling upgrades to avoid potential issues.

**Comment by Testorakel** [comment]
In version 2.0.1, the 'AI Commands' do not work under Linux anymore. The selection dialog is not displayed. In version 1.4.1, everything works perfectly.

**Comment by nbonamy** [comment]
Sorry about that. Hopefully fixed in 2.0.2. Please keep me updated.

**Comment by irosyadi** [comment]
Okay, so the original issue is fixed in Witsy version 2.0.2 on Windows 10 – great!

However, now there's a new bug. After generating a response, the "replace" and "insert" options are broken. "Replace" just deletes the existing text, and "Insert" doesn't actually add anything.

**Comment by nbonamy** [comment]
Ok sorry: rushed this. So before I release another one which is still missing something, can you please check
https://github.com/nbonamy/witsy/releases/tag/v2.0.3

Thanks!

**Comment by irosyadi** [comment]
I looked it over and it's working great, thanks!
