### ISSUE TITLE
Command redesign problems

### ISSUE THREAD

**Issue by irosyadi** [nbonamy/witsy#19]
In Windows (Witsy 1.24.0), the new AI command redesign didn't work for inserting, replacing, and chatting, either by clicking or using the hotkeys (keys 'i' or 'r'). However, the copy command (key 'c') works.

**Comment by nbonamy** [comment]
Hi. Just tested again on Windows on my side and it is working fine. Can you provide more specifics on what is happening? Thanks!

https://github.com/user-attachments/assets/215be616-2eec-4296-9500-fdccbfdf0276

**Comment by nbonamy** [comment]
Sorry about that. Should be fixed in just released 1.24.1. Please confirm 😀

**Comment by irosyadi** [comment]
Thank you, Nic, for your quick response. The hotkeys for copy ('c'), insert ('i'), and replace ('r') work well. However, the hotkeys for read, chat, and write do not work yet, although clicking them is okay. Also, I believe the functionality of the new command should be more thoroughly documented. Additionally, the action column in the command settings is no longer needed.

**Comment by nbonamy** [comment]
Should be fixed in latest 1.26.1

**Comment by irosyadi** [comment]
Good enough. However, the new chat shortcut ('n') still does not work. Another problem: the text is not copied by the 'ask me anything' command.

**Comment by nbonamy** [comment]
Sorry shortcut is S as "save". They are so not good that even me did not remember it!

**Comment by nbonamy** [comment]
About "Ask me anything" I was able to reproduce once and then not anymore but will keep you updated. Thanks!

**Comment by irosyadi** [comment]
Here's what happened on my computer: I tried the "Explain" command first, and it copied the text as intended; however, when I tried the "Ask me Anything" command, it did not copy the text.

https://github.com/user-attachments/assets/6d0525d2-bc81-4817-b89c-a70da21a2259

**Comment by irosyadi** [comment]
A little unrelated, but many commands and experts are activated automatically when Witsy is first installed. I think the majority of users only require a maximum of five experts. Disabling many experts after installation was slightly cumbersome. Therefore, it would be beneficial to either disable the majority of them by default or provide a smaller selection of experts.

**Comment by nbonamy** [comment]
> A little unrelated, but many commands and experts are activated automatically when Witsy is first installed. I think the majority of users only require a maximum of five experts. Disabling many experts after installation was slightly cumbersome. Therefore, it would be beneficial to either disable the majority of them by default or provide a smaller selection of experts.

I understand Witsy lacks documentation (looking for volunteers 😉) but did you see this?

<img width="635" alt="image" src="https://github.com/user-attachments/assets/5c6c044b-5ebf-4e35-aed1-0f73e5a457bd">

**Comment by irosyadi** [comment]
Ah, how come I can't see it?
> I understand Witsy lacks documentation (looking for volunteers 😉) but did you see this?

**Comment by nbonamy** [comment]
Which version are you running? (About Witsy in tray icon menu). Make sure you run the latest version. Download it from https://witsyai.com.

**Comment by irosyadi** [comment]
> Which version are you running? (About Witsy in tray icon menu). Make sure you run the latest version. Download it from [witsyai.com](https://witsyai.com).

I have seen the option to unselect all. Witsy 1.26.1.

**Comment by nbonamy** [comment]
> Here's what happened on my computer: I tried the "Explain" command first, and it copied the text as intended; however, when I tried the "Ask me Anything" command, it did not copy the text.
> 
>  2024-11-30.14-26-42.mp4

Should be fixed (or at least occurring less often) in just released 1.26.2.
